### ISSUE TITLE
Broken date range iteration?

### ISSUE THREAD

**Issue by ap** [PerlToolsTeam/psc#1]
https://github.com/davorg/psc/blob/c896356009b491d9302edbb49cf4718115eca8c6/get_psc#L19-L20

Wouldn’t that fail to iterate previous years past the month in the current year?

It seems to me you want something like

````perl
for my $y (2021 .. $this_y) {
  for my $m ('01' .. ($y == $this_y ? $this_m : '12')) {
````

or maybe

````perl
for my $y (2021 .. $this_y) {
  my $end_m = $y == $this_y ? $this_m : '12';
  for my $m ('01' .. $end_m) {
````

or whatever along these lines.

Am I missing something?

**Comment by ap** [comment]
Ah, I stopped reading short of this line:
https://github.com/davorg/psc/blob/c896356009b491d9302edbb49cf4718115eca8c6/get_psc#L24

So the minimal fix would be
````perl
for my $m ('01' .. '12') {
````

Though I would prefer my `$end_m` suggestion and deleting that `last` on the basis that that conditional lives in the outer rather than the inner loop, i.e. is only executed once per whole year rather than once for every single month.

**Comment by davorg** [comment]
This is just a scratch program that I used when trying to build the first list of meetings. It's not used at all now. I should just remove it from the repo.
