### ISSUE TITLE
List of PSC meeting attendees

### ISSUE THREAD

**Issue by book** [PerlToolsTeam/psc#15]
Most meeting summaries include a list of who attended them, so this is definitely public information.

I'm thinking about producing such a list of attendees for each meeting (including guests). Would that be interesting for the site? We had 2 in-person meetings so far, which might also be nice to highlight.

**Comment by davorg** [comment]
That would definitely be interesting. If you could produce a JSON file keyed on the meeting number, I'd be happy to add it to `psc.json` and display the information on the site.

**Comment by book** [comment]
Here's the format I can produce:

```
{
   "attendees" : [
      "Paul Evans",
      "Philippe Bruhat",
      "Ricardo Signes"
   ],
   "blog" : "https://blogs.perl.org/users/psc/2023/03/this-week-in-psc-100.html",
   "invitees" : [
      "Peter Krawczyk"
   ],
   "num" : "100",
   "scribe" : "Paul Evans"
},
```

Would that work for you?

You'll note the additional fields for `invitees` (we did invite non-PSC people from time to time), `scribe` (whoever sent the email to p5p), and `blog` (since we started posting our summaries to blogs.perl.org).

I'll need a bit more time to figure out the data for the meetings before my time (I attended starting from number 70).

**Comment by book** [comment]
I should have the full data soon. I can patch the JSON file directly in a PR, if the additional key names listed above suit you.

**Comment by davorg** [comment]
That all looks great. Thanks.

**Comment by davorg** [comment]
Done - see #19
