### ISSUE TITLE
Reverse list order?

### ISSUE THREAD

**Issue by ap** [PerlToolsTeam/psc#2]
As long as the list is short I can see sorting it in ascending order, but once it’s longer than a screen it seems more useful to me to have the summary of the most recent meeting at the top.

There’s a reason weblogs (and pre-algorithmic timelines on the web in general) settled on reverse chronological order 🙂

**Comment by davorg** [comment]
Yeah. I'm getting close to rewriting this from scratch (I've never got on with Jekyll) and I'll add a sorting option at that time.
