### ISSUE TITLE
Direct link to one of the tabs

### ISSUE THREAD

**Issue by book** [PerlToolsTeam/psc#20]
The table now has two tabs, one for the meetings, and one for the members.

Is it possible to link directly to one of the tabs? The "Meetings" tab is the default, and I haven't been able to find an anchor to open it directly on the "Members" page.

**Comment by davorg** [comment]
Yeah, that's certainly something I'd like to add too.

It's going to need me to write a little bit of Javascript. I'll have a look at it tomorrow.

**Comment by davorg** [comment]
Looks like this works now - https://psc.perlhacks.com/#members

And, for completeness - https://psc.perlhacks.com/#meetings
